# Generated by Django 3.2 on 2022-11-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_auto_20221103_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subjects_start_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subjects_stop_time',
            field=models.IntegerField(default=0),
        ),
    ]
